export type Lang = 'en' | 'pt';

export const content = {
  en: {
    nav: {
      background: 'Background',
      committee: 'Committee',
      assessment: 'Assessment',
      objectives: 'Objectives',
      programme: 'Programme',
      portal: 'Owners Portal',
      contact: 'Contact',
      cta: 'Download Proxy Form',
    },
    hero: {
      eyebrow: 'Campo Real · AGM 2026',
      title: 'Alternative Proposal for the Administration Committee',
      subtitle: 'Objectives, Ideas & Proposal — offering owners a clear choice, a structured plan, and a governance approach fully aligned with our regulating documents.',
      meetingDetails: [
        'Annual General Meeting of the 2 Condominiums of the Campo Real Resort',
        'Aldeamento Turistico (AT) and Conjunto Turistice CT',
        'Will be held on 18th of June 2026 at 3.00pm at',
        'The Grupo Despattive da Casa do Povo do Turcital, Rua Dr. Carlos Ahrends, No. 29, 2565-801, Turgital Portugal',
      ],
      meetingDisclaimer: "If you can't make the AGM and would like to support positive change, you can download the attached Proxy form email camporealowners@gmail.com and we will help you complete the form and have it collected.",
      cta: 'Download Proxy Form',
      ctaSub: 'Learn more about our proposal',
    },
    background: {
      label: 'Background',
      title: 'Dear Campo Real Owners,',
      paragraphs: [
        'Campo Real operates under the framework of a <strong>Condomínio Turístico (CT)</strong>, which includes the Hotel & Golf Course. The Condomínio Aldeamento consists of the Villas, Townhouses, and 9 Apartment blocks. All properties at Campo Real are tourist properties, but approximately <strong>65% have Habitation licences</strong> from the tax authority. The Condominium is governed by the Título Constitutivo and applicable legal regulations.',
        'An Administration Committee is elected by owners and is responsible for governance and decision-making. The Management Company is a contracted service provider responsible for day-to-day operational support.',
        'Since the recovery process began in 2013, important progress has been achieved. However, concerns have emerged regarding transparency, communication, long-term planning, and financial performance. According to available audit reports, the condominium has been <strong>operating at a loss for the past 5 years</strong>.',
        'In full compliance with internal regulations, a formal request was submitted in time for this proposed committee to be included on the AGM agenda for voting. The notice issued on 23 February did not include this item — the present Administration rejected the proposed committee and would not let owners vote on the matter.',
        'For this reason, a group of motivated owners decided to stand for election to form a new Administration Committee, including a representative from <strong>SummerCamp (Explorer)</strong> — the entity that owns the hotel.',
        'Our objective is not division. It is to offer owners a clear choice, a structured plan, and a governance approach fully aligned with our regulating documents, so that owners can have a voice in how their condominium is run.',
        '<strong>With your support, we can build a stronger and more sustainable future for Campo Real.</strong>',
      ],
    },
    committee: {
      label: 'Proposed Committee',
      title: 'Meet the Team',
      subtitle: 'All owners will be represented — by property type, nationality, and personal & professional experience. The Administration will be contactable.',
      support: 'With exclusive support of SummerCamp (Explorer)',
      bioCta: 'Read bio',
      members: [
        {
          name: 'Andrew Gamble',
          role: 'Construction Director',
          bio: [
            'This year, Andrew and his family celebrate 20 years of having their home at Campo Real, making them one of the long-standing international families within the resort community.',
            'Having seen Campo Real evolve over two decades, Andrew believes the condominium is now at an important moment where a more open, transparent and community-focused approach to governance is needed to help protect its long-term future.',
            'Andrew and his wife Ingrid became particularly involved in community life when owners and residents wanted to organise a simple family gathering within the communal spaces at Campo Real. Conditions imposed by the current Administration Committee were considered by many residents to be excessive for a small community event, including requirements for a full-time hired security company and for organisers to accept responsibility for the potential cost of draining and refilling the swimming pool.',
            'Rather than allow this to prevent the community from coming together, Andrew and Ingrid welcomed owners, residents and families into their home, helping create one of the first independent resident gatherings within the resort and encouraging a stronger sense of community across Campo Real.',
            'Over the years, Andrew has seen many owners become frustrated by poor communication, lack of transparency and the feeling that owners are often excluded rather than encouraged to participate in condominium affairs.',
            'Andrew believes Campo Real should be run fully in accordance with the Título Constitutivo and Portuguese condominium law, with proper governance, clearer financial accountability and fair representation for all owners, both Portuguese and international.',
            'He also hopes to help create a more welcoming and collaborative environment where owners feel listened to, respected and encouraged to contribute positively to the future of the resort.',
            'His vision is to help ensure Campo Real remains a sustainable, well-managed and thriving community for owners, residents and future generations.',
          ],
        },
        {
          name: 'Diogo Vaz Martins',
          role: 'Project Manager',
          bio: [
            'Diogo is a young father of two with a professional background in finance who has been living in Campo Real for the last two years as an apartment owner and resident.',
            'After attending his first AGM, Diogo became increasingly concerned about the way the condominium was being managed and the lack of long-term planning for the apartment blocks and wider community.',
            'His concerns first arose when trying to install an EV charging point for his family car and being told that it was not possible. From there, he began looking more closely into the wider situation affecting apartment owners, including insurance issues, fire safety concerns and the general management of the blocks.',
            'Wanting to better understand the financial position of the condominium, Diogo spent considerable time reviewing the accounts and was shocked by the apparent lack of meaningful cash reserves and the absence of clear long-term financial planning.',
            'Rather than simply complaining, Diogo decided to stand for election because he believes Campo Real can and should be managed better — with transparent accounting, proper long-term maintenance planning, responsive management, improved communication and a stronger focus on the needs of residents and families.',
            'He would particularly like to see improvements in children’s facilities, practical solutions for EV charging, safer and better managed apartment blocks, and a more open and professional approach to condominium governance.',
            'Diogo’s vision is to help create a well-run, financially responsible and welcoming Campo Real where families can grow, prosper and enjoy a true sense of community.',
          ],
        },
        {
          name: 'André Vilas Boas',
          role: 'Hotel Representative',
          bio: [
            'Understanding the Role of André Vilas Boas and the Structure of the Condominium at Campo Real',
            'Many owners have asked questions about the role of André Vilas Boas within the proposed Administration Committee and how the condominium structure at Campo Real actually operates.',
            'Under the Título Constitutivo of Campo Real, the overall condominium structure is the CT — Conjunto Turístico — which is the controlling entity of the resort. The AT — Aldeamento Turístico — sits within the wider CT structure.',
            'Although CT and AT each have their own NIF numbers and separate areas of responsibility, they form part of the same overall condominium framework established under the Título Constitutivo and Portuguese law.',
            'The controlling interest of CT is linked to Explorer Investments/DHM, as the entity connected to the hotel and tourism operation of the resort. For this reason, there is a mandatory representative position connected to that controlling entity within the condominium structure.',
            'André Vilas Boas attends the Administration Committee as the representative connected to Summercamp/DHM/Explorer under this framework. His inclusion is therefore not an elected owner position in the same way as the remaining committee members.',
            'It is also important for owners to understand that Explorer/DHM have made clear that they do not wish to directly run the condominium on a day-to-day basis. Their stated position is that owners themselves should democratically manage the condominium through a properly functioning administration operating in accordance with the Título Constitutivo and Portuguese condominium law.',
            'This was demonstrated earlier this year when the controlling entity refused to support the AGM process after the proposed alternative committee was excluded from the agenda for owner voting. Their position was that owners should be allowed a fair and democratic process.',
            'The proposed new administration team believes it is important that Campo Real now moves forward with proper governance, transparency, legally compliant accounting structures and constructive cooperation between owners, CT, AT and the hotel, so that the condominium can be managed fairly and sustainably for the future.',
          ],
        },
        {
          name: 'Clive J. Poorter',
          role: 'IT Systems Consultant',
          bio: [
            'Clive Poorter chose Campo Real as his retirement home and has been living at the resort for just over two years.',
            'As a keen golfer and active member of the community, Clive quickly developed a strong appreciation for the unique lifestyle, facilities and international atmosphere that make Campo Real such a special place to live. At the same time, he also became increasingly aware of the need for better communication, stronger organisation and more transparent condominium management.',
            'Clive has become particularly concerned by the lack of properly separated financial accounting between CT, AT and the apartment blocks, despite these structures being clearly established within the Título Constitutivo. He believes owners deserve much clearer information about how funds are allocated and how decisions affecting the resort are being made.',
            'With a strong background in IT and systems management, Clive believes Campo Real would benefit greatly from more modern communication systems, improved financial reporting and a more professional and organised approach to long-term planning and maintenance.',
            'He also sees the importance of building constructive relationships between owners, the golf course, the hotel and the wider resort infrastructure so that Campo Real can move forward in a positive and cooperative way.',
            'Rather than focusing on division, Clive wants to help create a more transparent, efficient and forward-thinking administration that listens to owners and plans responsibly for the future.',
            'His vision is to help build a financially responsible, well-managed and welcoming Campo Real where owners can enjoy both the lifestyle and long-term security of their investment and community.',
          ],
        },
        {
          name: 'Casimiro Gonçalves',
          role: 'Neurosurgeon',
          bio: [
            'Dr. Casimiro Gonçalves is one of the most respected and long-standing members of the Campo Real community, having lived at the resort for almost 20 years.',
            'As an experienced neurosurgeon, Casimiro brings calmness, objectivity and the ability to analyse complex situations carefully and thoughtfully. He is widely known as someone who listens carefully, avoids unnecessary conflict and focuses on practical solutions that benefit the wider community.',
            'Over the years, Casimiro has seen Campo Real change considerably and believes the condominium now needs a broader and more balanced administration capable of combining experience, innovation and modern governance.',
            'He feels strongly that owners deserve better communication, greater transparency and more professional long-term planning to ensure that Campo Real continues to develop positively and sustainably for future generations.',
            'Representing many Portuguese owners within the resort, Casimiro believes that a successful condominium should bring together owners from all backgrounds and nationalities with a shared goal of protecting and improving the community.',
            'His vision is to help create a modern, well-managed and inclusive Campo Real where owners feel secure, informed and proud to be part of the community.',
          ],
        },
      ],
    },
    assessment: {
      label: 'Assessment',
      title: 'How We See Things Now',
      disclaimer: 'These points relate to systems and future strategy, not to personal criticism of the current Administration, whose efforts we acknowledge and respect.',
      items: [
        {
          num: '01',
          title: 'Depreciation of the Condominium',
          points: [
            'Decline in property values relative to market trends in the surrounding area',
            'Deterioration of common areas and general appearance',
            'Lack of asset investment with no initiatives for cost saving',
            'No strategic plan — no long-term planning',
          ],
        },
        {
          num: '02',
          title: 'Financial Situation at Risk',
          points: [
            'Impact of audited accumulated losses (CT+AT)',
            'No planning for future financial sustainability',
            'No open tender processes',
            'Lack of transparency with accounts, costs and revenue',
            'Unnecessary and/or uncontrolled expenses',
          ],
        },
        {
          num: '03',
          title: 'Operational Inefficiencies & Transparency',
          points: [
            'Poor communication and engagement practices alienating owners',
            'Trust between owners and management at an all-time low',
            'No service-focused approach for property owners',
            'No performance standards or accountability',
            'No clear documentation of decisions and processes',
          ],
        },
        {
          num: '04',
          title: 'Compliance & Legal Obligations',
          points: [
            'Company authorisation and regulatory compliance',
            'Insurance coverage and policy',
            'Fire systems in apartment blocks disconnected',
            'Administrative liability and risk exposure',
            'Follow-up on formal legal and enforcement communications',
          ],
        },
      ],
    },
    objectives: {
      label: 'Mandate Objectives',
      title: 'With Your Vote',
      items: [
        {
          title: 'Sustainable Enhancement',
          body: 'Promote the sustainable enhancement of the Resort through structured, forward-looking development supported by a rigorous and professional management model.',
        },
        {
          title: 'Financial Stewardship',
          body: 'Ensure efficient and responsible financial stewardship, with a disciplined focus on cost optimisation, long-term value creation, and financial sustainability — ensuring all owners are listened to and respected.',
        },
        {
          title: 'Infrastructure & Common Areas',
          body: 'Prioritise the maintenance, upgrading, and improvement of infrastructure and common areas to preserve and strengthen the quality, reputation, and market value of your home.',
        },
        {
          title: 'Transparency & Governance',
          body: 'Reinforce a culture of transparency, accountability, and good governance in all operational and financial matters.',
        },
        {
          title: 'Strategic Planning',
          body: 'Define and implement a clear multi-year strategic plan, based on measurable objectives, realistic timelines, and responsible execution.',
        },
      ],
    },
    programme: {
      label: 'Programme',
      title: '7 Pillars, 20 Proposals',
      subtitle: 'Working with owners — not dictating.',
      pillars: [
        {
          num: '01',
          title: 'Governance & Legal Obligations',
          body: 'Define a robust governance model. Organise an open tender process. Review compliance with legal obligations (e.g. insurances). Ensure the Annual owners meeting allows owners to express their views, held at a suitable time for maximum participation.',
        },
        {
          num: '02',
          title: 'Professional Operational Management',
          body: 'Define service standards and implement regular meetings between owners and the management company. Ensure a service-focused approach for all property owners, with clear performance standards and accountability.',
        },
        {
          num: '03',
          title: 'Transparency & Communication',
          body: 'Create a Condominium Portal where owners can submit requests, view updates, their account, and all invoices. Increased involvement of owners in setting priorities, with engagement facilitated by apartment block.',
        },
        {
          num: '04',
          title: 'Financial, Legal & Risk Management',
          body: 'Robust accounting with audits and transparent, open details on expenses. Separated and detailed annual budget targeting expense optimisation. Transparent and separate accounting for CT, AT, and each apartment block.',
        },
        {
          num: '05',
          title: 'Investments in Infrastructure',
          body: 'Economic feasibility assessment for solar panels. Apartment owners access to EV charging in line with current Portuguese law. Children\'s playground. Investigate owner-proposed initiatives: car parking, shade protection, heated pools, outdoor gym.',
        },
        {
          num: '06',
          title: 'Resort Development & Long-Term Planning',
          body: 'Development of a five-year plan. Working with Apartment owners to manage the apartment blocks, ensuring sufficient funds from maintenance contributions are set aside to meet future maintenance costs.',
        },
        {
          num: '07',
          title: 'Strengthening the Owners–Hotel Relationship',
          body: 'Development and improvement of existing partnership conditions (e.g. Green Card). Improvement of the relationship with the Hotel / Discovery / Explorer.',
        },
      ],
    },
    mission: {
      label: 'Our Mission',
      quote: 'To provide financial transparency, clear and accountable communication, professional and service-oriented management, responsible stewardship of condominium finances, and the long-term protection and enhancement of our property values — <strong>always acting in the collective interest of all Owners.</strong>',
      disclaimer: 'This proposal represents a forward-looking vision for Campo Real based on owner perspectives. It is offered with respect for the work of the current Administration and in the spirit of open, democratic discussion among owners.',
    },
    portal: {
      label: 'Coming Soon',
      title: 'Your Owners Portal',
      subtitle: 'If elected, one of our first commitments is to build a dedicated digital portal for all Campo Real owners — a single place to stay informed, engaged, and connected.',
      badge: 'In Development',
      sections: [
        { icon: 'calendar', title: 'Community Events', desc: 'Stay up to date with social events, owner meetings, and resort activities.' },
        { icon: 'hotel', title: 'Hotel Events', desc: 'Browse upcoming hotel events, offers, and partner programmes.' },
        { icon: 'file-text', title: 'AGM Documents', desc: 'Access all AGM minutes, resolutions, financial reports, and audits.' },
        { icon: 'shield', title: 'Insurance Policies', desc: 'View your condominium insurance documents and coverage details.' },
        { icon: 'message-square', title: 'Suggestions', desc: 'Submit ideas and feedback directly to the Administration Committee.' },
        { icon: 'user', title: 'My Account', desc: 'Manage your owner profile, payments, and property information.' },
        { icon: 'map', title: 'Planning Info', desc: 'Access planning permissions, infrastructure projects, and development updates.' },
      ],
    },
    contact: {
      label: 'Contact',
      title: 'Your Vote Matters',
      subtitle: 'If you are unable to attend the AGM in person, please consider granting your proxy to us to ensure you are represented and your voice is heard.',
      body: 'Andrew, Casimiro, Clive, Diogo & André look forward to working with all owners to build a community we can all be proud of.',
      email: 'camporealowners@gmail.com',
      proxyBtn: 'Download Proxy Form',
      proxyNote: 'Select your form — Individual or Company, in English or Portuguese. Opens in a new tab ready to print and sign.',
      questionNote: 'Any questions? Get in touch.',
    },
  },

  pt: {
    nav: {
      background: 'Contexto',
      committee: 'Comité',
      assessment: 'Diagnóstico',
      objectives: 'Objectivos',
      programme: 'Programa',
      portal: 'Portal de Proprietários',
      contact: 'Contacto',
      cta: 'Descarregar Procuração',
    },
    hero: {
      eyebrow: 'Campo Real · AGM 2026',
      title: 'Proposta Alternativa para o Comité de Administração',
      subtitle: 'Objectivos, Ideias & Projecto — oferecendo aos proprietários uma escolha clara, um plano estruturado e um modelo de governação plenamente alinhado com os nossos documentos reguladores.',
      meetingDetails: [
        'Annual General Meeting of the 2 Condominiums of the Campo Real Resort',
        'Aldeamento Turistico (AT) and Conjunto Turistice CT',
        'Will be held on 18th of June 2026 at 3.00pm at',
        'The Grupo Despattive da Casa do Povo do Turcital, Rua Dr. Carlos Ahrends, No. 29, 2565-801, Turgital Portugal',
      ],
      meetingDisclaimer: "If you can't make the AGM and would like to support positive change, you can download the attached Proxy form email camporealowners@gmail.com and we will help you complete the form and have it collected.",
      cta: 'Descarregar Procuração',
      ctaSub: 'Saiba mais sobre a nossa proposta',
    },
    background: {
      label: 'Contexto',
      title: 'Caros Proprietários do Campo Real,',
      paragraphs: [
        'O Campo Real opera no âmbito de um <strong>Condomínio Turístico (CT)</strong>, que integra o Hotel e o Campo de Golfe. O Condomínio Aldeamento é composto pelas Moradias Isoladas, Moradias em Banda e 9 blocos de Apartamentos. Todas as propriedades no Campo Real são classificadas como turísticas; contudo, aproximadamente <strong>65% dispõem de licença de habitação</strong> emitida pela Autoridade Tributária.',
        'A Comissão de Administração é eleita anualmente pelos proprietários e é responsável pela governação e tomada de decisões. A Empresa de Gestão é uma entidade contratada, incumbida de assegurar o apoio operacional diário.',
        'Desde o início do processo de recuperação, em 2013, foram alcançados progressos relevantes. Contudo, têm surgido preocupações relativamente à transparência, à comunicação, ao planeamento de longo prazo e ao desempenho financeiro. De acordo com os relatórios de auditoria disponíveis, o condomínio tem registado <strong>prejuízos significativos nos últimos cinco anos</strong>.',
        'Em total conformidade com o regulamento interno, foi submetido atempadamente um pedido formal para que esta comissão proposta fosse incluída na ordem de trabalhos da Assembleia Geral. Contudo, a convocatória emitida em 23 de fevereiro não incluiu este ponto — a atual Administração rejeitou a proposta e não permitiu que a mesma fosse apresentada aos proprietários para votação.',
        'Por este motivo, um grupo de proprietários motivados decidiu apresentar-se a eleições para constituir uma nova Comissão de Administração, incluindo um representante da <strong>SummerCamp (Explorer)</strong> — entidade proprietária do hotel.',
        'O nosso objetivo não é criar divisão. Pretendemos oferecer aos proprietários uma escolha clara, um plano estruturado e um modelo de governação plenamente alinhado com os documentos reguladores, permitindo que os proprietários tenham uma voz ativa na forma como o seu condomínio é gerido.',
        '<strong>Com o seu apoio vamos construir um futuro sólido e mais sustentável para o Campo Real.</strong>',
      ],
    },
    committee: {
      label: 'Comité Proposto',
      title: 'Conheça a Equipa',
      subtitle: 'Todos os proprietários vão estar representados — por tipologia de propriedade, nacionalidade e experiência pessoal e profissional. Este Comité estará disponível e acessível.',
      support: 'Com o apoio exclusivo da SummerCamp (Explorer)',
      bioCta: 'Ler bio',
      members: [
        {
          name: 'Andrew Gamble',
          role: 'Director de Obra/Construção',
          bio: [
            'Apresentamos o nosso primeiro candidato à Comissão de Administração',
            'Este ano, Andrew e a sua família celebram 20 anos desde que passaram a ter a sua casa no Campo Real, tornando-se uma das famílias internacionais de longa data da comunidade do resort.',
            'Tendo acompanhado a evolução do Campo Real ao longo de duas décadas, Andrew acredita que o condomínio atravessa atualmente um momento importante, em que é necessária uma abordagem de gestão mais aberta, transparente e focada na comunidade, de forma a ajudar a proteger o seu futuro a longo prazo.',
            'Andrew e a sua esposa Ingrid envolveram-se particularmente na vida da comunidade quando proprietários e residentes quiseram organizar um simples convívio familiar nos espaços comuns do Campo Real. As condições impostas pela atual Comissão de Administração foram consideradas por muitos residentes excessivas para um pequeno evento comunitário, incluindo a exigência de contratar uma empresa de segurança a tempo inteiro e de os organizadores assumirem responsabilidade pelos potenciais custos de esvaziar e voltar a encher a piscina.',
            'Em vez de permitir que isso impedisse a comunidade de se juntar, Andrew e Ingrid abriram as portas da sua casa a proprietários, residentes e famílias, ajudando a criar um dos primeiros encontros independentes de residentes dentro do resort e incentivando um espírito de comunidade mais forte em todo o Campo Real.',
            'Ao longo dos anos, Andrew viu muitos proprietários tornarem-se frustrados com a falta de comunicação, falta de transparência e com a sensação de que os proprietários são frequentemente excluídos, em vez de encorajados a participar nos assuntos do condomínio.',
            'Andrew acredita que o Campo Real deve ser gerido em total conformidade com o Título Constitutivo e com a lei portuguesa do condomínio, com uma governação adequada, maior transparência financeira e representação justa para todos os proprietários, portugueses e internacionais.',
            'Espera também ajudar a criar um ambiente mais acolhedor e colaborativo, onde os proprietários se sintam ouvidos, respeitados e incentivados a contribuir positivamente para o futuro do resort.',
            'A sua visão é ajudar a garantir que o Campo Real continue a ser uma comunidade sustentável, bem gerida e próspera para proprietários, residentes e futuras gerações.',
          ],
        },
        {
          name: 'Diogo Vaz Martins',
          role: 'Gestor de Projecto',
          bio: [
            'Conheçam Diogo Martins — candidato à nova proposta de Comissão de Administração do Campo Real.',
            'O Diogo é pai de duas crianças e tem uma formação profissional na área financeira. Vive no Campo Real há dois anos como proprietário e residente num apartamento.',
            'Depois de participar na sua primeira Assembleia Geral, começou a ficar cada vez mais preocupado com a forma como o condomínio estava a ser gerido e com a falta de planeamento a longo prazo, tanto para os blocos de apartamentos como para toda a comunidade.',
            'As suas preocupações começaram quando tentou instalar um ponto de carregamento para o carro elétrico da família e lhe foi dito que isso não seria possível. A partir daí, começou a analisar mais atentamente outras questões que afetam os proprietários dos apartamentos, incluindo seguros, questões de segurança contra incêndios e a gestão geral dos blocos.',
            'Com vontade de compreender melhor a situação financeira do condomínio, o Diogo dedicou bastante tempo à análise das contas e ficou preocupado com a aparente falta de reservas financeiras significativas, a ausência de planeamento financeiro de longo prazo e a dificuldade que muitos proprietários têm em perceber claramente a verdadeira situação financeira do condomínio.',
            'Em vez de apenas criticar de fora, o Diogo decidiu avançar como candidato porque acredita que o Campo Real pode e deve ser gerido de uma forma mais aberta, profissional e transparente — com contas mais claras, planeamento adequado de manutenção a longo prazo, uma gestão mais presente e eficiente, melhor comunicação e uma maior atenção às necessidades das famílias e dos residentes.',
            'Gostaria particularmente de ver melhorias nas infraestruturas para crianças, soluções práticas para carregamento de veículos elétricos, blocos de apartamentos mais seguros e melhor geridos, e um condomínio onde os proprietários se sintam verdadeiramente informados e incluídos.',
            'A visão do Diogo é ajudar a criar um Campo Real bem gerido, financeiramente responsável e acolhedor, onde as famílias possam crescer, prosperar e desfrutar de um verdadeiro sentido de comunidade.',
          ],
        },
        {
          name: 'André Vilas Boas',
          role: 'Representante do Hotel',
          bio: ['André representa a posição da Summercamp/DHM/Explorer no enquadramento do CT, promovendo cooperação entre proprietários, hotel e resort.'],
        },
        {
          name: 'Clive J. Poorter',
          role: 'Consultor Sistemas IT',
          bio: [
            'Conheça Clive Poorter — candidato à nova Comissão de Administração do Campo Real.',
            'Clive Poorter escolheu o Campo Real como a sua casa de reforma e vive no resort há pouco mais de dois anos.',
            'Sendo um entusiasta do golfe e um membro ativo da comunidade, Clive rapidamente desenvolveu uma forte apreciação pelo estilo de vida único, pelas instalações e pelo ambiente internacional que tornam o Campo Real um local tão especial para viver. Ao mesmo tempo, começou também a perceber cada vez mais a necessidade de uma melhor comunicação, de uma organização mais forte e de uma gestão condominial mais transparente.',
            'Clive tem-se mostrado particularmente preocupado com a falta de separação adequada da contabilidade financeira entre o CT, o AT e os blocos de apartamentos, apesar destas estruturas estarem claramente definidas no Título Constitutivo. Acredita que os proprietários merecem informações muito mais claras sobre a forma como os fundos são distribuídos e como são tomadas as decisões que afetam o resort.',
            'Com uma sólida experiência em tecnologias de informação e gestão de sistemas, Clive acredita que o Campo Real beneficiaria enormemente de sistemas de comunicação mais modernos, de relatórios financeiros melhorados e de uma abordagem mais profissional e organizada ao planeamento e manutenção de longo prazo.',
            'Considera também fundamental desenvolver relações construtivas entre os proprietários, o campo de golfe, o hotel e as restantes infraestruturas do resort, para que o Campo Real possa avançar de forma positiva e cooperativa.',
            'Em vez de se focar na divisão, Clive quer ajudar a criar uma administração mais transparente, eficiente e orientada para o futuro, que ouça os proprietários e planeie de forma responsável para o futuro.',
            'A sua visão é ajudar a construir um Campo Real financeiramente responsável, bem gerido e acolhedor, onde os proprietários possam desfrutar tanto do estilo de vida como da segurança a longo prazo do seu investimento e da sua comunidade.',
          ],
        },
        {
          name: 'Casimiro Gonçalves',
          role: 'Neurocirurgião',
          bio: [
            'Conheça o Dr. Casimiro Gonçalves — candidato à nova Comissão de Administração do Campo Real.',
            'O Dr. Casimiro Gonçalves é um dos membros mais respeitados e com maior ligação histórica à comunidade do Campo Real, residindo no resort há quase 20 anos.',
            'Enquanto neurocirurgião experiente, Casimiro traz serenidade, objetividade e capacidade de analisar situações complexas de forma cuidadosa e ponderada. É amplamente reconhecido como alguém que sabe ouvir, evita conflitos desnecessários e procura soluções práticas que beneficiem a comunidade no seu conjunto.',
            'Ao longo dos anos, Casimiro assistiu a grandes mudanças no Campo Real e acredita que o condomínio necessita agora de uma administração mais abrangente e equilibrada, capaz de combinar experiência, inovação e uma gestão moderna.',
            'Defende firmemente que os proprietários merecem melhor comunicação, maior transparência e um planeamento profissional de longo prazo, de forma a garantir que o Campo Real continue a evoluir de forma positiva e sustentável para as futuras gerações.',
            'Representando muitos proprietários portugueses dentro do resort, Casimiro acredita que um condomínio de sucesso deve unir proprietários de diferentes origens e nacionalidades em torno de um objetivo comum: proteger e valorizar a comunidade.',
            'A sua visão passa por ajudar a criar um Campo Real moderno, bem gerido e inclusivo, onde os proprietários se sintam seguros, informados e orgulhosos de fazer parte da comunidade.',
          ],
        },
      ],
    },
    assessment: {
      label: 'Diagnóstico',
      title: 'Como Vemos as Coisas Hoje',
      disclaimer: 'Estes pontos referem-se a sistemas e estratégia futura, não a uma crítica pessoal à atual Administração, cujo empenho reconhecemos e respeitamos.',
      items: [
        {
          num: '01',
          title: 'Desvalorização do Condomínio',
          points: [
            'Valor das propriedades a descer face à evolução na zona envolvente',
            'Degradação das zonas comuns e aparência geral do Resort',
            'Falta de investimento estrutural e passividade na gestão/redução de custos',
            'Ausência de plano plurianual',
          ],
        },
        {
          num: '02',
          title: 'Situação Financeira Limite',
          points: [
            'Significativos prejuízos acumulados (CT+AT) nos últimos 6 anos',
            'Ausência de planeamento para sustentabilidade futura do Condomínio',
            'Custos descontrolados/desnecessários',
            'Falta de transparência das contas, custos e proveitos',
          ],
        },
        {
          num: '03',
          title: 'Gestão Operacional Ineficiente e Pouco Transparente',
          points: [
            'Práticas deficientes de comunicação e envolvimento que afastam os proprietários',
            'Quebra de vínculo de confiança dos Proprietários',
            'Falta de orientação ao serviço aos Proprietários',
            'Ausência de métricas de avaliação e responsabilidade',
            'Decisões e processos não documentados',
          ],
        },
        {
          num: '04',
          title: 'Obrigações Legais e Compliance',
          points: [
            'Autorização da Empresa e Conformidade Regulamentar',
            'Cobertura de Seguro e Apólice',
            'Sistemas de Incêndio nos Blocos de Apartamentos Desligados',
            'Responsabilidade Administrativa e Exposição ao Risco',
            'Acompanhamento de Comunicações Formais de Natureza Jurídica e Fiscalizadora',
          ],
        },
      ],
    },
    objectives: {
      label: 'Objectivos do Mandato',
      title: 'Com o Seu Voto',
      items: [
        {
          title: 'Valorização Sustentável',
          body: 'Promover a valorização sustentável do Resort e das respetivas propriedades através de um desenvolvimento estruturado e orientado para o futuro, sustentado por um modelo de gestão rigoroso e profissional.',
        },
        {
          title: 'Gestão Financeira Responsável',
          body: 'Assegurar uma gestão financeira eficiente e responsável, com foco disciplinado na otimização de custos, na criação de valor a longo prazo e na sustentabilidade financeira, garantindo que todos os proprietários são ouvidos e respeitados.',
        },
        {
          title: 'Infraestruturas & Áreas Comuns',
          body: 'Priorizar a manutenção, modernização e melhoria das infraestruturas e das áreas comuns do Resort, de forma a preservar e reforçar a qualidade, a reputação e o valor de mercado da sua propriedade.',
        },
        {
          title: 'Transparência & Governação',
          body: 'Reforçar uma cultura de transparência, responsabilidade e boa governação em todos os assuntos operacionais e financeiros.',
        },
        {
          title: 'Planeamento Estratégico',
          body: 'Definir e implementar um plano estratégico plurianual claro, baseado em objetivos mensuráveis, calendários realistas e execução responsável.',
        },
      ],
    },
    programme: {
      label: 'Programa',
      title: '7 Pilares, 20 Propostas',
      subtitle: 'A trabalhar com os proprietários — não a ditar.',
      pillars: [
        {
          num: '01',
          title: 'Definição de Governance e Obrigações Legais',
          body: 'Definição de um robusto modelo de governance. Lançamento de concurso (Tender) para a gestão operacional. Revisão de cumprimento de obrigações legais (e.g. Seguros). Garantir que a AGM é agendada para dia não útil para aumentar a participação.',
        },
        {
          num: '02',
          title: 'Gestão Operacional Profissionalizada',
          body: 'Definição de standards de serviço e reporte regular. Garantir que Proprietários podem expressar a sua visão e preocupações de forma aberta durante a AGM. Comunicação clara e objectiva com Proprietários a nível da gestão operacional.',
        },
        {
          num: '03',
          title: 'Promoção da Transparência e Comunicação',
          body: 'Criação de um portal do Condómino para submeter pedidos, enviar sugestões e consultar a conta corrente com o Condomínio. Aumento do envolvimento dos proprietários dos Blocos de Apartamentos na definição de prioridades.',
        },
        {
          num: '04',
          title: 'Gestão Financeira, Legal e de Risco',
          body: 'Gestão financeira robusta, auditada de forma independente e transparente. Orçamento detalhado e separado com foco na redução de custos. Contabilidade individual (CT, AT e por Bloco de Apartamentos).',
        },
        {
          num: '05',
          title: 'Investimento em Infraestruturas',
          body: 'Análise de viabilidade para painéis solares. Reavaliação de carregadores EV nas garagens. Expansão do parque infantil. Recuperar iniciativas antigas rejeitadas (ex: estacionamento, proteção solar, piscinas aquecidas, ginásio exterior).',
        },
        {
          num: '06',
          title: 'Estratégia / Plano Plurianual de Desenvolvimento',
          body: 'Elaboração de um plano plurianual (5 anos). Aumento do envolvimento dos proprietários dos Blocos de Apartamentos para as necessidades futuras de manutenções, garantindo fundos suficientes.',
        },
        {
          num: '07',
          title: 'Aprofundamento da Relação Condóminos–Hotel',
          body: 'Melhoria da relação com Hotel/Discovery. Desenvolvimento e melhoria das condições da(s) parceria(s) existentes (ex: Greencard).',
        },
      ],
    },
    mission: {
      label: 'A Nossa Missão',
      quote: 'Assegurar transparência financeira, uma comunicação clara e responsável, uma gestão profissional e orientada para o serviço, uma administração prudente das finanças do condomínio e a proteção e valorização sustentada, a longo prazo, do valor das nossas propriedades — <strong>atuando sempre no interesse coletivo de todos os Proprietários.</strong>',
      disclaimer: 'Esta proposta representa uma visão orientada para o futuro do Campo Real, baseada na perspetiva dos proprietários. É apresentada com respeito pelo trabalho da atual Administração e num espírito de diálogo aberto e democrático entre os proprietários.',
    },
    portal: {
      label: 'Em Breve',
      title: 'O Seu Portal de Proprietários',
      subtitle: 'Se eleitos, um dos nossos primeiros compromissos é criar um portal digital dedicado a todos os proprietários do Campo Real — um único lugar para se manter informado, envolvido e ligado à comunidade.',
      badge: 'Em Desenvolvimento',
      sections: [
        { icon: 'calendar', title: 'Eventos da Comunidade', desc: 'Fique a par de eventos sociais, reuniões de proprietários e atividades do resort.' },
        { icon: 'hotel', title: 'Eventos do Hotel', desc: 'Consulte os próximos eventos do hotel, ofertas e programas de parceiros.' },
        { icon: 'file-text', title: 'Documentos da AGM', desc: 'Aceda a todas as atas, resoluções, relatórios financeiros e auditorias.' },
        { icon: 'shield', title: 'Apólices de Seguro', desc: 'Consulte os documentos de seguro do condomínio e os detalhes de cobertura.' },
        { icon: 'message-square', title: 'Sugestões', desc: 'Envie ideias e feedback diretamente ao Comité de Administração.' },
        { icon: 'user', title: 'A Minha Conta', desc: 'Gira o seu perfil de proprietário, pagamentos e informações da propriedade.' },
        { icon: 'map', title: 'Informação de Planeamento', desc: 'Aceda a licenças de construção, projetos de infraestrutura e atualizações de desenvolvimento.' },
      ],
    },
    contact: {
      label: 'Contacto',
      title: 'O Seu Voto Conta',
      subtitle: 'Caso não lhe seja possível comparecer presencialmente na Assembleia Geral, solicitamos que considere conceder-nos a sua procuração, de forma a assegurar a sua representação.',
      body: 'O Andrew, Casimiro, Clive, Diogo e André estão empenhados em colaborar com todos os proprietários para construir uma comunidade da qual todos nos possamos orgulhar.',
      email: 'camporealowners@gmail.com',
      proxyBtn: 'Descarregar Procuração',
      proxyNote: 'Selecione o formulário — Individual ou Empresa, em Inglês ou Português. Abre num novo separador para imprimir e assinar.',
      questionNote: 'Alguma questão? Entre em contacto.',
    },
  },
};
